### ISSUE TITLE
sample pcap file

### ISSUE THREAD

**Issue by irina-nitu** [FOXNEOAdvancedTechnology/smpte2110-20-dissector#1]
Hi,

Can you please share a sample pcap file?

Regards,
Irina

**Comment by philippdorn** [comment]
You can use sample files from the EBUtech LIST. Its also here on Github:

Look in sample data: https://github.com/ebu/pi-list

**Comment by NEOAdvancedTechnology** [comment]
Also see: https://github.com/FOXNEOAdvancedTechnology/ST2110_pcap_zoo
